CREATE DATABASE TEST

USE TEST

CREATE TABLE PRODUCT
(PRODUCTID INT,
 PRODUCTTYPE VARCHAR(50),
 BRANDNAME VARCHAR(50),
 PRICE FLOAT,
 DISCOUNTEDPRICE FLOAT
);

INSERT INTO PRODUCT(PRODUCTID,PRODUCTTYPE,BRANDNAME,PRICE,DISCOUNTEDPRICE) VALUES(1,'electronics','reliance','200.50','195.00');

INSERT INTO PRODUCT VALUES(2,'electronics','phillips',100,90);

INSERT INTO PRODUCT VALUES(3,'electronics','lg',130,110);

INSERT INTO PRODUCT VALUES(4,'Bakery','moti Bakery',200,180);

INSERT INTO PRODUCT VALUES(5,'Bakery','john',300,280);

INSERT INTO PRODUCT VALUES(6,'Clothing','reliance',250,230);

INSERT INTO PRODUCT VALUES(7,'Grocery','D-Mart',500,450);

INSERT INTO PRODUCT VALUES(8,'Grocery','Blinkit',300,290);

INSERT INTO PRODUCT VALUES(9,'Grocery','reliance',400,380);

INSERT INTO PRODUCT VALUES(10,'medical','sun pharma',1000,970);


SELECT * FROM PRODUCT

-- SELECT COUNT(PRODUCTID) FROM PRODUCT;
-- SELECT COUNT(PRODUCTID) FROM PRODUCT WHERE PRODUCTTYPE='electronics' ;
-- SELECT MAX(DISCOUNTEDPRICE) FROM PRODUCT;
-- SELECT MIN(PRICE) FROM PRODUCT WHERE PRODUCTTYPE='Grocery';
-- SELECT PRODUCTTYPE FROM PRODUCT WHERE BRANDNAME='reliance';
-- SELECT COUNT(DISTINCT BRANDNAME) FROM PRODUCT;
-- SELECT MAX(PRICE) FROM PRODUCT WHERE BRANDNAME='RELIANCE';


--SELECT TOP 1 * FROM PRODUCT WHERE PRODUCTTYPE='electronics' ORDER BY PRODUCTID DESC 

ALTER DATABASE TEST MODIFY NAME = PRACTICE;
